### ISSUE TITLE
Doesn't install on PyCharm 2021.2.1

### ISSUE THREAD

**Issue by motiv-ncb** [lankydan/fairyfloss-intellij-theme#1]
Any chance this will get updated? Getting the following error when trying to install:

Error
Plugin 'Fairyfloss (version '0.0.1') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is PY-212.5080.64.

The link to the zip in the repo says it's version 0.0.2, but when I download it's still version 0.0.1.

Thanks!

**Comment by abbbey** [comment]
@motiv-ncb I had the same issue. I unpacked the zip and changed the build requirement to 212.* then repacked it. A little ugly but works until the upstream gets fixed.
[fairyfloss-intellij-theme.zip](https://github.com/lankydan/fairyfloss-intellij-theme/files/7165215/fairyfloss-intellij-theme.zip)

**Comment by lankydan** [comment]
Hi, sorry about the late fix. A new version should be released now - https://plugins.jetbrains.com/plugin/16502-fairyfloss/versions

**Comment by abbbey** [comment]
thanks! I appreciate you maintaining this (even though we all have busy lives) :)

**Comment by lankydan** [comment]
> thanks! I appreciate you maintaining this (even though we all have busy lives) :)

@abbbey no worries. Make sure to update to 0.0.3 since I noticed an issue the other day which I've sorted now.
